font_family      JetBrainsMono Nerd Font Mono
bold_font        JetBrainsMono Nerd Font Mono Extra Bold
bold_italic_font JetBrainsMono Nerd Font Mono Extra Bold Italic

# Set window layout
enabled_layouts splits:split_axis=horizontal

# New windows (splits)
map ctrl+alt+h launch --location=vsplit
map ctrl+alt+j launch --location=hsplit
map ctrl+alt+k launch --location=hsplit
map ctrl+alt+l launch --location=vsplit

# Move focus
map alt+h neighboring_window left
map alt+j neighboring_window down
map alt+k neighboring_window up
map alt+l neighboring_window right

# Resize windows
map alt+shift+h resize_window narrower
map alt+shift+l resize_window wider
map alt+shift+j resize_window shorter
map alt+shift+k resize_window taller

disable_ligatures always
